# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Build
on:
  push:
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          # Can move to 17 when 1.6.0 is released:
          # https://issues.apache.org/jira/browse/GUACAMOLE-1716
          java-version: '11'
          distribution: temurin
          cache: maven

      - name: Build webclient
        run: mvn package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
        working-directory: guacamole

      - name: Build extension
        run: mvn package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
        working-directory: extensions/jupyternotatre-auth

      - name: Copy artifacts
        run: |
          mkdir artifacts
          cp guacamole/target/*.war artifacts/
          cp extensions/jupyternotatre-auth/target/*.jar artifacts/

      - uses: actions/upload-artifact@v3
        with:
          name: guacamole
          path: artifacts
          if-no-files-found: error

    # if: startsWith(github.ref, 'refs/tags')
